### ISSUE TITLE
Versión de sso_login instalada produce problemas en el 1er migration en development-edx

### ISSUE THREAD

**Issue by fsologureng** [eol-uchile/edx-staging#834]
https://github.com/eol-uchile/edx-staging/blob/b98c894a5649217b4b2001e8490a4c0538b8af55/requirements/apps.txt#L10C8-L10C92

**Comment by fsologureng** [comment]
@tomaspemora podemos ya pasar a la última versión en la rama eol de staging?

**Comment by tomaspemora** [comment]
@fsologureng En la rama de eol-staging no debería estar sso_login. Solo debiese estar en ou-staging. Deberíamos sacarlo de aquí al igual que [course classification](https://github.com/eol-uchile/edx-staging/blob/eol-release/koa/requirements/apps.txt#L1) y [redfid logout](https://github.com/eol-uchile/edx-staging/blob/eol-release/koa/requirements/apps.txt#L13)

Respecto a la rama de open-release/koa, podría ser que lo pasemos, **en development**, pero funciona de manera conjunta con [cierta rama del tema de open uchile](https://github.com/open-uchile/open-uchile-theme/tree/ux-sso-patch). Lo que yo hice para evitar los errores en las migraciones fue eliminar las migraciones 002 y 003 y cambiar las dependencias de la 004:

```
dependencies = [
        ('eol_sso_login', '0001_initial'),
    ]
```

Aún no commiteo esto eso sí.

**Comment by fsologureng** [comment]
> @fsologureng En la rama de eol-staging no debería estar sso_login. Solo debiese estar en ou-staging. Deberíamos sacarlo de aquí al igual que [course classification](https://github.com/eol-uchile/edx-staging/blob/eol-release/koa/requirements/apps.txt#L1) y [redfid logout](https://github.com/eol-uchile/edx-staging/blob/eol-release/koa/requirements/apps.txt#L13)
> 
> Respecto a la rama de open-release/koa, podría ser que lo pasemos, **en development**, pero funciona de manera conjunta con [cierta rama del tema de open uchile](https://github.com/open-uchile/open-uchile-theme/tree/ux-sso-patch). Lo que yo hice para evitar los errores en las migraciones fue eliminar las migraciones 002 y 003 y cambiar las dependencias de la 004:
> 
> ```
> dependencies = [
>         ('eol_sso_login', '0001_initial'),
>     ]
> ```
> 
> Aún no commiteo esto eso sí.

Yo sacaría lo que hay que sacar de la rama para eol (staging) y dejaría lo que funcione bien en la rama ou-staging. 

Por otro lado, el tema que yo reporto acá, es que el hash que está ahora en esta rama (staging) no tiene aún mi parche para que el migration 0001_initial funcione bien, porque el original de Luchín está mal hecho, recuerdas?

Voy a revisar el hash de oustaging para ver si el migration 0001 está parchado o no...

**Comment by fsologureng** [comment]
> @fsologureng En la rama de eol-staging no debería estar sso_login. Solo debiese estar en ou-staging. Deberíamos sacarlo de aquí al igual que [course classification](https://github.com/eol-uchile/edx-staging/blob/eol-release/koa/requirements/apps.txt#L1) y [redfid logout](https://github.com/eol-uchile/edx-staging/blob/eol-release/koa/requirements/apps.txt#L13)

Me entró una duda: dónde probamos redfid_logout si no es en eol-staging?

**Comment by tomaspemora** [comment]
no lo probamos :/ porque es de Redfid (norteamericano). La buena noticia es que Vicente de CMM me indicó que con la API que creo para redfid https://github.com/cmmedu/redfid-edx-api ya no es necesario redfid_logout. Deberíamos borrarlo de aquí y archivar el repo.
